name: Build and run functional tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
      - develop-sync
  pull_request:

jobs:
  build_application:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@jca/update_reusable_build
    with:
      upload_app_binaries_artifact: "compiled_app_binaries"
      builder: ledger-app-builder

  functional_tests:
    name: Run tests
    needs: build_application
    uses: ./.github/workflows/functional_tests.yml
    with:
      download_app_binaries_artifact: "compiled_app_binaries"
